name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Building version $VERSION"
          
          # Create dist directory
          mkdir -p dist
          
          # Build for multiple platforms
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=$VERSION -s -w" -o dist/cli-recover-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=$VERSION -s -w" -o dist/cli-recover-darwin-arm64 .
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=$VERSION -s -w" -o dist/cli-recover-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=$VERSION -s -w" -o dist/cli-recover-linux-arm64 .
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=$VERSION -s -w" -o dist/cli-recover-windows-amd64.exe .

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > checksums.txt
          cat checksums.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## CLI-Recover ${{ github.ref }}
            
            ### Installation
            
            1. Download the binary for your platform
            2. Make it executable: `chmod +x cli-recover-*`
            3. Move to your PATH: `sudo mv cli-recover-* /usr/local/bin/cli-recover`
            
            ### Supported Platforms
            - macOS (Intel): `cli-recover-darwin-amd64`
            - macOS (Apple Silicon): `cli-recover-darwin-arm64`
            - Linux (x64): `cli-recover-linux-amd64`
            - Linux (ARM64): `cli-recover-linux-arm64`
            - Windows (x64): `cli-recover-windows-amd64.exe`
            
            ### Verify Download
            
            Check the checksums.txt file to verify your download.
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/cli-recover-*
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}